### ISSUE TITLE
Colors differ from terminal style guide

### ISSUE THREAD

**Issue by nekowinston** [catppuccin/blink#1]
Hi there! 👋

Thanks for the port!
I noticed that the background color seems off - I think `Mantle` is supposed to be `Base`, e.g. `#181825` -> `#1e1e2e` for Mocha. The style guide for terminals has just been [updated today](https://github.com/catppuccin/catppuccin/blob/dev/docs/style-guide.md), in the `catppuccin/catppuccin` dev branch.

**Comment by rithikasilva** [comment]
Just updated the background colours to those on the style guide for terminals :)
